object MainForm: TMainForm
  Left = 100
  Top = 100
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  BorderWidth = 2
  Caption = 'POPWIL_HPU'
  ClientHeight = 317
  ClientWidth = 452
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -17
  Font.Name = 'Tahoma'
  Font.Style = []
  Menu = MainMenu1
  Position = poDesigned
  OnClose = FormClose
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  OnShow = FormShow
  PixelsPerInch = 144
  TextHeight = 21
  object Bevel1: TBevel
    Tag = 255
    Left = 0
    Top = 36
    Width = 1118
    Height = 2
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
  end
  object CommSta_Shape1: TShape
    Tag = 255
    Left = 12
    Top = -6
    Width = 18
    Height = 33
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Brush.Color = clActiveBorder
    Pen.Width = 2
    Shape = stCircle
  end
  object Panel1: TPanel
    Tag = 255
    Left = 12
    Top = 36
    Width = 1058
    Height = 303
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    TabOrder = 0
    object GroupBox1: TGroupBox
      Tag = 255
      Left = 0
      Top = 0
      Width = 288
      Height = 290
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -17
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentColor = False
      ParentFont = False
      TabOrder = 0
      object ResetSta_Shape: TShape
        Tag = 255
        Left = 153
        Top = 26
        Width = 45
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clGreen
        Pen.Width = 2
        Shape = stCircle
        Visible = False
      end
      object Label1: TLabel
        Left = 24
        Top = 92
        Width = 38
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Filter'
      end
      object Filter_Shape1: TShape
        Tag = 255
        Left = 104
        Top = 84
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clGreen
        Pen.Width = 2
        Shape = stCircle
      end
      object Filter_Shape2: TShape
        Tag = 255
        Left = 131
        Top = 84
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clGreen
        Pen.Width = 2
        Shape = stCircle
        Visible = False
      end
      object Filter_Shape3: TShape
        Tag = 255
        Left = 158
        Top = 84
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clGreen
        Pen.Width = 2
        Shape = stCircle
        Visible = False
      end
      object Filter_Shape4: TShape
        Tag = 255
        Left = 185
        Top = 84
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clGreen
        Pen.Width = 2
        Shape = stCircle
        Visible = False
      end
      object Label2: TLabel
        Left = 108
        Top = 68
        Width = 9
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = '1'
      end
      object Label3: TLabel
        Left = 135
        Top = 68
        Width = 9
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = '2'
        Visible = False
      end
      object Label4: TLabel
        Left = 162
        Top = 68
        Width = 9
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = '3'
        Visible = False
      end
      object Label5: TLabel
        Left = 189
        Top = 68
        Width = 9
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = '4'
        Visible = False
      end
      object PressureCaptionLabel: TLabel
        Left = 24
        Top = 140
        Width = 64
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Pressure'
      end
      object PressureUnitLabel: TLabel
        Tag = 255
        Left = 228
        Top = 128
        Width = 31
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'MPa'
      end
      object TemprUnitLabel: TLabel
        Tag = 255
        Left = 228
        Top = 173
        Width = 18
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #176'C'
      end
      object TemprCaptionLabel: TLabel
        Left = 24
        Top = 168
        Width = 47
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Temp.'
      end
      object HYLUnitLabel: TLabel
        Tag = 255
        Left = 228
        Top = 201
        Width = 17
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = '%'
      end
      object HYLCaptionLabel: TLabel
        Left = 24
        Top = 201
        Width = 38
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Level'
      end
      object QUnitLabel: TLabel
        Tag = 255
        Left = 228
        Top = 230
        Width = 42
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'L/min'
      end
      object QCaptionLabel: TLabel
        Left = 24
        Top = 234
        Width = 35
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Flow'
      end
      object Label14: TLabel
        Tag = 255
        Left = 60
        Top = -24
        Width = 57
        Height = 21
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Label14'
      end
      object PressureEdit: TEdit
        Tag = 255
        Left = 99
        Top = 126
        Width = 104
        Height = 37
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Color = clInfoBk
        Font.Charset = ANSI_CHARSET
        Font.Color = clBlack
        Font.Height = -29
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Text = '0.0'
      end
      object TemprEdit: TEdit
        Tag = 255
        Left = 99
        Top = 162
        Width = 104
        Height = 37
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Color = clInfoBk
        Font.Charset = ANSI_CHARSET
        Font.Color = clBlack
        Font.Height = -29
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
        Text = '10.0'
      end
      object HYLEdit: TEdit
        Tag = 255
        Left = 99
        Top = 195
        Width = 104
        Height = 37
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Color = clInfoBk
        Font.Charset = ANSI_CHARSET
        Font.Color = clBlack
        Font.Height = -29
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        Text = '50.0'
      end
      object QEdit: TEdit
        Tag = 255
        Left = 99
        Top = 228
        Width = 104
        Height = 37
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Color = clInfoBk
        Font.Charset = ANSI_CHARSET
        Font.Color = clBlack
        Font.Height = -29
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        ReadOnly = True
        TabOrder = 3
        Text = '3.0'
      end
      object ResetPanel: TPanel
        Left = 60
        Top = 21
        Width = 158
        Height = 38
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        BorderStyle = bsSingle
        Caption = 'Reset/All Stop'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -17
        Font.Name = #21326#25991#20013#23435
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 4
        OnClick = ResetPanelClick
      end
    end
    object PumpGroupBox1: TGroupBox
      Left = 275
      Top = 0
      Width = 171
      Height = 290
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Pump1'
      TabOrder = 1
      object PumpON_SpeedButton1: TSpeedButton
        Left = 23
        Top = 102
        Width = 97
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Pump ON'
        OnClick = PumpON_SpeedButton1Click
      end
      object PumpOFF_SpeedButton1: TSpeedButton
        Left = 23
        Top = 144
        Width = 97
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Pump OFF'
        OnClick = PumpOFF_SpeedButton1Click
      end
      object PressureHI_SpeedButton1: TSpeedButton
        Left = 23
        Top = 186
        Width = 97
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'High'
        OnClick = PressureHI_SpeedButton1Click
      end
      object PressureLow_SpeedButton1: TSpeedButton
        Left = 23
        Top = 228
        Width = 97
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = 'Low'
        OnClick = PressureLow_SpeedButton1Click
      end
      object PumpSta_Shape1: TShape
        Tag = 255
        Left = 129
        Top = 102
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clRed
        Pen.Width = 2
        Shape = stCircle
      end
      object PressureSta_Shape1: TShape
        Tag = 255
        Left = 129
        Top = 186
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clRed
        Pen.Width = 2
        Shape = stCircle
      end
    end
    object PumpGroupBox2: TGroupBox
      Left = 429
      Top = 0
      Width = 207
      Height = 290
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #27833#27893'2'
      TabOrder = 2
      Visible = False
      object PumpON_SpeedButton2: TSpeedButton
        Left = 36
        Top = 102
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #27833#27893#24320
      end
      object PumpOFF_SpeedButton2: TSpeedButton
        Left = 36
        Top = 144
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #27833#27893#20851
      end
      object PressureHI_SpeedButton2: TSpeedButton
        Left = 36
        Top = 186
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #39640#21387
      end
      object PressureLow_SpeedButton2: TSpeedButton
        Left = 36
        Top = 228
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #20302#21387
      end
      object PumpSta_Shape2: TShape
        Tag = 255
        Left = 164
        Top = 102
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clRed
        Pen.Width = 2
        Shape = stCircle
      end
      object PressureSta_Shape2: TShape
        Tag = 255
        Left = 164
        Top = 186
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clRed
        Pen.Width = 2
        Shape = stCircle
      end
    end
    object PumpGroupBox3: TGroupBox
      Left = 635
      Top = 0
      Width = 207
      Height = 290
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #27833#27893'3'
      TabOrder = 3
      Visible = False
      object PumpON_SpeedButton3: TSpeedButton
        Left = 36
        Top = 102
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #27833#27893#24320
      end
      object PumpOFF_SpeedButton3: TSpeedButton
        Left = 36
        Top = 144
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #27833#27893#20851
      end
      object PressureHI_SpeedButton3: TSpeedButton
        Left = 36
        Top = 186
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #39640#21387
      end
      object PressureLow_SpeedButton3: TSpeedButton
        Left = 36
        Top = 228
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #20302#21387
      end
      object PumpSta_Shape3: TShape
        Tag = 255
        Left = 164
        Top = 102
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clRed
        Pen.Width = 2
        Shape = stCircle
      end
      object PressureSta_Shape3: TShape
        Tag = 255
        Left = 164
        Top = 186
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clRed
        Pen.Width = 2
        Shape = stCircle
      end
    end
    object PumpGroupBox4: TGroupBox
      Left = 851
      Top = 0
      Width = 207
      Height = 290
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #27833#27893'4'
      TabOrder = 4
      Visible = False
      object PumpON_SpeedButton4: TSpeedButton
        Left = 36
        Top = 102
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #27833#27893#24320
      end
      object PumpOFF_SpeedButton4: TSpeedButton
        Left = 36
        Top = 144
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #27833#27893#20851
      end
      object PressureHI_SpeedButton4: TSpeedButton
        Left = 36
        Top = 186
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #39640#21387
      end
      object PressureLow_SpeedButton4: TSpeedButton
        Left = 36
        Top = 228
        Width = 98
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Caption = #20302#21387
      end
      object PumpSta_Shape4: TShape
        Tag = 255
        Left = 164
        Top = 102
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clRed
        Pen.Width = 2
        Shape = stCircle
      end
      object PressureSta_Shape4: TShape
        Tag = 255
        Left = 164
        Top = 186
        Width = 18
        Height = 33
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Brush.Color = clRed
        Pen.Width = 2
        Shape = stCircle
      end
    end
  end
  object Button1: TButton
    Left = 348
    Top = -2
    Width = 84
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Button1'
    TabOrder = 1
    Visible = False
    OnClick = Button1Click
  end
  object ClientSocket1: TClientSocket
    Tag = 255
    Active = False
    Address = '192.168.0.3'
    ClientType = ctNonBlocking
    Port = 502
    Left = 16
    Top = 200
  end
  object MainMenu1: TMainMenu
    Tag = 255
    Left = 64
    object N2: TMenuItem
      Tag = 255
      AutoHotkeys = maManual
      Caption = ' &Systerm'
      object Options_Item: TMenuItem
        Tag = 255
        Caption = '&Option'
        OnClick = Options_ItemClick
      end
      object Quit_Item: TMenuItem
        Tag = 255
        Caption = '&Quit'
        OnClick = Quit_ItemClick
      end
    end
    object N1: TMenuItem
      Tag = 255
      AutoHotkeys = maManual
      Caption = '&Help'
      object About_Item: TMenuItem
        Tag = 255
        Caption = '&About'
        OnClick = About_ItemClick
      end
    end
  end
  object PLC_Comm: TComm
    Tag = 255
    CommName = 'COM1'
    BaudRate = 9600
    ParityCheck = False
    Outx_CtsFlow = False
    Outx_DsrFlow = False
    DtrControl = DtrEnable
    DsrSensitivity = False
    TxContinueOnXoff = True
    Outx_XonXoffFlow = True
    Inx_XonXoffFlow = True
    ReplaceWhenParityError = False
    IgnoreNullChar = False
    RtsControl = RtsEnable
    XonLimit = 10
    XoffLimit = 10
    ByteSize = _8
    Parity = None
    StopBits = _1
    XonChar = #2
    XoffChar = #3
    ReplacedChar = #0
    ReadIntervalTimeout = 10
    ReadTotalTimeoutMultiplier = 0
    ReadTotalTimeoutConstant = 0
    WriteTotalTimeoutMultiplier = 0
    WriteTotalTimeoutConstant = 0
    OnReceiveData = PLC_CommReceiveData
    Left = 88
    Top = 200
  end
  object DspTimer: TTimer
    Tag = 255
    Enabled = False
    Interval = 300
    OnTimer = DspTimerTimer
    Left = 32
  end
  object IdModBus_To_PLC: TIdModBusClient
    Tag = 255
    ConnectTimeout = 3000
    ReadTimeout = 3000
    TimeOut = 3000
    Left = 120
  end
end
