// Do not edit. This file is machine generated by the Resource DLL Wizard.

library HPU;

{ITE} {DFMFileType} {About.dfm}
{ITE} {DFMFileType} {FatekPLC.dfm}
{ITE} {DFMFileType} {Main.dfm}
{ITE} {DFMFileType} {ParaSet.dfm}
{ITE} {RCFileType} {Win32\Release\HPU_DRC.rc}

{$R 'About.dfm' 'AboutForm:TForm'}
{$R 'FatekPLC.dfm' 'FatekPLCForm:TForm'}
{$R 'Main.dfm' 'MainForm:TForm'}
{$R 'ParaSet.dfm' 'ParaSetForm:TForm'}
{$R 'Win32\Release\HPU_DRC.res' 'Win32\Release\HPU_DRC.rc'}

{$E DEU}

begin
end.
